#!/bin/sh

# Replace localhost addresses with proper
find docs -type f -print0 | xargs -0 sed -i 's/https:\/\/www.zdenekborovec.cz/http:\/\/www.zdenekborovec-dev.cz/g'
find docs -type f -print0 | xargs -0 sed -i 's/https:\/\/assets.zdenekborovec.cz\/common/http:\/\/assets.zdenekborovec-dev.cz\/common/g'
find docs -type f -print0 | xargs -0 sed -i 's/https:\/\/zdenekborovec.cz/http:\/\/zdenekborovec-dev.cz/g'
find assets -type f -print0 | xargs -0 sed -i 's/https:\/\/www.zdenekborovec.cz/http:\/\/www.zdenekborovec-dev.cz/g'
find assets -type f -print0 | xargs -0 sed -i 's/https:\/\/assets.zdenekborovec.cz\/common/http:\/\/assets.zdenekborovec-dev.cz\/common/g'
find assets -type f -print0 | xargs -0 sed -i 's/https:\/\/zdenekborovec.cz/http:\/\/zdenekborovec-dev.cz/g'
